dist: bionic
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - make
    - gcc
    - bison
    - flex
    - rake
    - git
    - curl
    - ca-certificates
cache:
  directories:
    - mruby
    - build/mrbgems
script:
- rake test
